### ISSUE TITLE
Decision needed: codes starting with numerical values

### ISSUE THREAD

**Issue by jvsoest** [jvsoest/PBDW2018_hackathon#2]
The current R2RML tool doesn't accept terminology codes starting with a numeric value (e.g. roo:100018). Hence we temporarily added the letter Pxxxxxx and Cxxxxxx for respectively predicates and classes.

We need to decide whether this is good behaviour (to start with letters), or if we fix the R2RML tool

**Comment by andredekker** [comment]
I would change the ROO as this starting with numbers might hurt is in future tools

**Comment by jvsoest** [comment]
Decision made, discussion moved to ROO repository.
